//! Generated DMA wire DTOs — one module per device family.
//!
//! Each child module is generated by `cargo xtask gen-wires` from
//! the matching `user/wirespecs/<family>.toml`. The generated types
//! are `#[repr(transparent)]` newtypes over `[u8; N]` with typed
//! field accessors that handle BE/LE byte order per-field; the
//! per-type `dma_value_impl!` invocation is emitted alongside so the
//! sealed-trait + const_assert padding check rides along by
//! construction.
//!
//! Driver and userlib code should NOT import from here directly —
//! family modules like `lockjaw_types::virtio` and
//! `lockjaw_types::fwcfg` re-export the relevant DTOs via
//! `pub use crate::wire::<family>::*;` so import paths stay stable
//! across the codegen split.

pub mod fwcfg;
pub mod virtio;
