[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=--gc-sections",
    "-Z", "emit-stack-sizes",
]

[alias]
xtask = "run --package xtask --target aarch64-apple-darwin --"
