#![no_std]
#![no_main]
// Driver-crate body writes zero `unsafe` blocks AND zero
// `#[allow(unsafe_code)]` attributes. The macro-generated boot
// stubs in `lockjaw_userlib::boot_stub!` are the single audited
// location for the boot-entry attributes; the macro's expansion is
// the only place `#[allow(unsafe_code)]` appears for this build.
//
// `#![deny]` (not `#![forbid]`) so the macro-emitted per-item
// allows on `#[no_mangle]` and `#[link_section]` are honoured.
// Acceptance grep:
// `grep -rn 'allow(unsafe_code)' user/uart-driver/src/`
// MUST return nothing.
#![deny(unsafe_code)]

use lockjaw_userlib::driver_runtime::{run_event_server, DriverCtx, EventEngine};
use lockjaw_userlib::{driver_main, puts, sys_exit, PL011_HASH};
use lockjaw_mmio::region::MappedRegs;
use lockjaw_regs::pl011::{Flag, Imsc, Pl011};

// ---------------------------------------------------------------------------
// PL011 helpers (the only "device behaviour" the driver expresses —
// the rest of the register surface is the generated lockjaw_regs::pl011).
// ---------------------------------------------------------------------------

/// Write a byte to the UART, spinning while the TX FIFO is full.
fn uart_putc(regs: &Pl011, c: u8) {
    while regs.flag().contains(Flag::TXFF) {
        core::hint::spin_loop();
    }
    regs.write_data(c as u32);
}

/// Write a string to the UART, converting `\n` to `\r\n` (PL011 expects
/// the explicit CR for terminals that don't auto-translate).
fn uart_puts(regs: &Pl011, s: &str) {
    for b in s.bytes() {
        if b == b'\n' {
            uart_putc(regs, b'\r');
        }
        uart_putc(regs, b);
    }
}

// ---------------------------------------------------------------------------
// Event engine — implements the canonical event-loop driver shape.
// Owns the typed MMIO region; on_ipc forwards a byte to TX, on_irq
// drains the RX FIFO. The framework owns the sys_wait_any loop, the
// IRQ-threshold bookkeeping, the IPC receive/reply syscalls, and the
// bit-mask constants — this driver has ZERO raw `sys_*` calls outside
// `sys_exit` in the panic handler.
// ---------------------------------------------------------------------------

struct UartEngine {
    regs: MappedRegs<Pl011>,
}

impl UartEngine {
    fn regs(&self) -> &Pl011 { self.regs.regs() }
}

impl EventEngine for UartEngine {
    fn on_ipc(&mut self, msg: u64) -> u64 {
        // IPC TX request: the message word is the byte to send.
        uart_putc(self.regs(), msg as u8);
        0
    }

    fn on_irq(&mut self) {
        // Drain the RX FIFO; echo each character (CR also produces LF).
        while !self.regs().flag().contains(Flag::RXFE) {
            let ch = (self.regs().read_data() & 0xFF) as u8;
            uart_putc(self.regs(), ch);
            if ch == b'\r' {
                uart_putc(self.regs(), b'\n');
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Driver main — invoked by the driver_main! macro after boot, probe,
// claim, IRQ bind. Enables PL011's RX interrupt, prints a UART1 banner,
// then hands off to `run_event_server`.
// ---------------------------------------------------------------------------

fn uart_main(ctx: DriverCtx<Pl011>) -> ! {
    let mut engine = UartEngine { regs: ctx.regs };

    // Enable PL011 RX interrupt. Bit ops over Imsc (BitOr is emitted
    // by the generated flags newtype); we OR RXIM into the current
    // mask, preserving TXIM and any future bits the spec adds.
    engine.regs().set_imsc(engine.regs().imsc() | Imsc::RXIM);

    // Kernel-debug-channel confirmation FIRST: proves driver code
    // reached this point regardless of UART1 state. Only AFTER that
    // do we write the UART1 banner through `uart_putc`'s unbounded
    // TXFF spin-loop. On a board with a marginal PL011 (or any TX-
    // broken state) the spin would otherwise hang the driver here
    // and the "server ready" log line would never appear, leading
    // to a misdiagnosis as init failure. See docs/tracking/tech-debt.md
    // ("PL011 TX wait is unbounded") for the deadline-bounded
    // follow-up that makes the spin itself fail-fast.
    puts("uart-driver: server ready\n");
    uart_puts(engine.regs(), "uart-driver: UART1 active\n");

    run_event_server(
        &mut engine,
        ctx.server_ep,
        ctx.irq_notif,
        ctx.irq_initial_threshold,
    )
}

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    puts("uart-driver: PANIC\n");
    sys_exit();
}

// ---------------------------------------------------------------------------
// Driver boot — generated by the macro. The macro's expansion site
// is the single location where the driver build carries
// `#[allow(unsafe_code)]`; the driver crate body is unsafe-free.
// ---------------------------------------------------------------------------

driver_main! {
    name = "uart-driver",
    hash = LOCKJAW_SOURCE_HASH,
    probe_hash = PL011_HASH,
    layout = Pl011,
    main = uart_main,
}
